### ISSUE TITLE
JAX unit tests incorrectly trying to unpack `flax.linen.Module.init()` return value

### ISSUE THREAD

**Issue by yhtang** [NVIDIA/TransformerEngine#352] opened 2023-08-02 07:22 UTC
As identified in [JAX-Toolbox CI](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5735056345/job/15543552618#step:7:813), `flax.linen.Module.init()` returns value using the following schema:
```
{
  "params": {
    ...
  },
  ...
}
```
, where the value of the `param` key is another dict.

However, the JAX unit tests in TE [assumes the value is a 2-tuple](https://github.com/NVIDIA/TransformerEngine/blob/95ec156057d000c1ba5f26d3671e5ef7c149f763/tests/jax/test_layer.py#L37).

Could someone please update the tests?

Reproduction steps:
1. Launch container: 
   ```
   docker run --gpus all -it ghcr.io/nvidia/jax-te:nightly-2023-08-01@sha256:0abc912287b766ea3769ac153926368de338518b6f3796815932b7d779c43368 bash
   ```
2. Inside the container:
   ```
   cd /opt/transformer-engine/
   export SKIP_HEAD_INSTALLS=1
   pip install -e '/opt/transformer-engine[test]' pytest-reportlog fiddle git+https://github.com/google/praxis
   pytest "tests/jax/test_layer.py::TestEncoderLayer::test_forward[attrs0-float32-data_shape0]"
   ```

**Comment by yhtang** [comment] 2023-08-02 07:24
Adding @terrykong for viz.

**Comment by zlsh80826** [comment] 2023-08-02 07:51
Reduced reproduce steps:
```
docker run --gpus all -it ghcr.io/nvidia/jax-te:nightly-2023-08-01@sha256:0abc912287b766ea3769ac153926368de338518b6f3796815932b7d779c43368 bash
pip install pytest
cd /opt/transformer-engine
pytest "tests/jax/test_layer.py::TestEncoderLayer::test_forward[attrs0-float32-data_shape0]"
```

**Comment by zlsh80826** [comment] 2023-08-02 07:58
The same steps can pass with `ghcr.io/nvidia/jax-te:nightly-2023-07-31`, the issue may come from the flax version. The flax version is `0.7.0` in 07-31 image, and flax version is `0.7.1` in 08-01 image. @mingxu1067 could you take a look on what's new in flax 0.7.1?

**Comment by mingxu1067** [comment] 2023-08-02 08:05
The root cause could be `removed FrozenDict section by @chiamp in https://github.com/google/flax/pull/3210`. The pop behavior of `FrozenDict` is slightly different with python built-in `dict`, `FrozenDict`'s `pop` reuturns two outputs, remaining `FrozenDict` and popped value, but python built-in `dict` only returns popped value then in-place delete it in orginal object.

**Comment by yhtang** [comment] 2023-08-02 17:45
The particular error seems to be gone. However, there are other places where FrozenDict was still expected/used, e.g.: https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5741541846/job/15562633991#step:7:809

**Comment by yhtang** [comment] 2023-08-02 17:53
Also there are errors in multi-GPU tests: https://gist.github.com/yhtang/6adf3b18c136cc20155f6d9daaa141e4

**Comment by mingxu1067** [comment] 2023-08-03 03:01
@yhtang, we did some fix to #353 by force pushing. Could you try this out again? All tests passed on my local side.
BTW, you might see an error ` RuntimeError: with_sharding_constraint requires a non-empty mesh if you are passing `PartitionSpec`s or `None` to shardings!`, this is fixed in #347 .

**Comment by yhtang** [comment] 2023-08-03 04:50
Great. Let's see how [this run](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5746725690) will turn out.

**Comment by yhtang** [comment] 2023-08-03 16:04
All unit tests passed now 😄 
Some JAX-Toolbox internal errors caused the multi-GPU tests to fail. I'll fix that and retry.

**Comment by yhtang** [comment] 2023-08-03 16:10
Confirming that integration also succeeded.

**Comment by mingxu1067** [comment] 2023-08-04 02:45
Close this, since #353 is merged and all unit-tests passed.

**Closed by mingxu1067** 2023-08-04 02:45 UTC
